groups:
- jobs:
  - deploy-wordpress
  name: wordpress-release
- name: deploy-wordpress 
  plan:
  - get: git-repo
    trigger: true
  - task: deploy-wordpress
    file: git-repo/pipeline/tasks/deploy-wordpress.yml
    params:
      BOSH_TARGET: {{bosh-target}}
      BOSH_USER: {{bosh-username}}
      BOSH_PASSWORD: {{bosh-password}}
resources:
- name: git-repo
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-git-branch}}
