---
platform: linux

image_resource:
  type: docker-image
  source: {repository: teamidefix/cf-deployments-pipeline}

inputs:
  - name: git-repo

params:
  BOSH_TARGET:
  BOSH_USER:
  BOSH_PASSWORD:

run:
  path: git-repo/pipeline/bin/deploy-wordpress.sh
