#!/bin/bash

JOB=wordpress
RUN_DIR=/var/vcap/sys/run/apache2
LOG_DIR=/var/vcap/sys/log/apache2
PIDFILE=$RUN_DIR/httpd.pid
CONF_DIR=/var/vcap/jobs/$JOB/config
APACHECTL=/var/vcap/packages/apache2/bin/apachectl
APSTART=/var/vcap/sys/log/apache2/start.log
NFS_SHARE=/var/vcap/shared

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    # link libphp into apache
    if [ ! -f /var/vcap/packages/apache2/modules/libphp5.so ]; then
      ln -s /var/vcap/packages/php5/modules/libphp5.so \
        /var/vcap/packages/apache2/modules/libphp5.so
    fi

    # link wordpress config file into wordpress package
    if [ ! -f /var/vcap/packages/wordpress/wp-config.php ]; then
      ln -s /var/vcap/jobs/wordpress/config/wp-config.php \
        /var/vcap/packages/wordpress/wp-config.php
    fi

    <% if_p("nfs_server.address", "nfs_server.share") do |nfs_address, nfs_share| %>
    modprobe nfs
    mkdir -p $NFS_SHARE

    cp -f /etc/default/nfs-common /etc/default/nfs-common.orig
    cp -f $CONF_DIR/nfs-common /etc/default/nfs-common

    cp -f $CONF_DIR/idmapd.conf /etc/idmapd.conf
    /etc/init.d/idmapd restart

    if grep -qs $NFS_SHARE /proc/mounts; then
      echo "Found NFS mount"
    else
      echo "Mounting NFS..."
      mount -o timeo=10,intr -t nfs4 <%= nfs_address %>:<%= nfs_share %> $NFS_SHARE
      if [ $? != 0 ]; then
        echo "Cannot mount NFS, exiting..."
        exit 1
      fi
    fi

    touch $NFS_SHARE/.nfs_test

    if [ $? != 0 ]; then
      echo "Failed to start: cannot write to NFS"
      exit 1
    fi
    <% end %>

    if [ ! -d $NFS_SHARE/wordpress ]; then
      mkdir -p $NFS_SHARE/wordpress
      cp -a /var/vcap/packages/wordpress/wp-content $NFS_SHARE/wordpress
      chown -R vcap:vcap $NFS_SHARE/wordpress
    fi

    $APACHECTL -f $CONF_DIR/httpd.conf -k start >> $APSTART 2>&1
    ;;

  stop)
    $APACHECTL -f $CONF_DIR/httpd.conf -k stop  >> $APSTART 2>&1
    ;;

  *)
  echo "Usage: ${JOB}_ctl {start|stop}" ;;
esac
exit 0
